### ISSUE TITLE
Spinner changes to 'wait' indefinitely after running code

### ISSUE THREAD

**Issue by ggorlen** [pykidos/pykidos.github.io#1]
To reproduce, visit https://pykidos.github.io/ and press <kbd>Ctrl</kbd>+<kbd>Enter</kbd>. Expected behavior is that the 'waiting' cursor will display momentarily as the code runs, then will revert to the default pointer. Instead, the cursor stays stuck on 'wait' indefinitely. Tested on FF and Chromium.

**Comment by rossant** [comment]
Is there an error message in the Javascript console?

**Comment by ggorlen** [comment]
Good question.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'interval')
    at Runner.get (runner.js:167:29)
    at Runner._run (runner.js:125:29)
    at async Runner.start (runner.js:210:19)
    at async Runner.run (runner.js:191:19)
```

The problem seems to be:

```js
let locale = getLocale(lang);
varName = locale[varName]; // crash
```

So `getLocale` cannot return null or undefined, but it's possible (as [this comment](https://github.com/pykidos/pykidos.github.io/issues/1#issuecomment-1998410517) indicates):

```js
if (lang) return LOCALIZATION[lang]; // could be undefined
```

**Comment by jackdoe** [comment]
I just ran into the same issue, for me there are two separate bugs one in locale.js you need to add:
```
-    if (lang) return LOCALIZATION[lang];
+    if (lang && LOCALIZATION[lang]) return LOCALIZATION[lang];
```
in getLocale() because my language is en-US, and then it does LOCLAIZATION['en'] which is undefined
 
and another is that print() gets overwritten with None from addLocale() in the added code header:

```
print = globals().get("print", None)
```

**Comment by rossant** [comment]
Duh. The bugs didn't show up during my tests on my French computers. :man_facepalming: Sorry about that. Should be fixed hopefully.
