### ISSUE TITLE
Some cells can't be updated if size is custom

### ISSUE THREAD

**Issue by bosnivan** [pykidos/pykidos.github.io#3]
Hi. For some custom sizes some cells can't be updated. I noticed it when I tried to make a traffic light example. In some cases multiple clicks are needed for cell update. There's no error in Dev Tools. By the way, the project is great. :)

![image](https://github.com/pykidos/pykidos.github.io/assets/27815255/9b4ff7ad-3a51-429a-a65d-c5ae91f87dbc)

**Comment by rossant** [comment]
Thank you for the bug report! Cell indexing was wrong, it should be fixed now. Please reopen if not!
